# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .action_action_type import ActionActionType
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class Action(UniversalBaseModel):
    title: str
    action_type: ActionActionType
    payload: typing.Optional[str] = None
    execute: typing.Optional[str] = None
    start_time: typing.Optional[str] = None
    end_time: typing.Optional[str] = None
    event_title: typing.Optional[str] = None
    event_description: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
