# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .card_style_payload_image_alignment import CardStylePayloadImageAlignment
from .card_style_payload_media_height import CardStylePayloadMediaHeight
from .card_style_payload_width import CardStylePayloadWidth
from .card_style_payload_orientation import CardStylePayloadOrientation
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class CardStylePayload(UniversalBaseModel):
    image_alignment: CardStylePayloadImageAlignment
    media_height: CardStylePayloadMediaHeight
    thumbnail_url: str
    width: CardStylePayloadWidth
    orientation: CardStylePayloadOrientation

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
