# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .action import Action
from .card_style_payload import CardStylePayload
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class CardPayload(UniversalBaseModel):
    title: str
    subtitle: typing.Optional[str] = None
    image_url: typing.Optional[str] = None
    buttons: typing.List[Action]
    card_style: CardStylePayload
    quick_replies: typing.Optional[typing.List[Action]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
