# This file was auto-generated by Fern from our API Definition.

import typing
from .rcs_message import RcsMessage
from .sms_message import SmsMessage

PostSendRequestBody = typing.Union[RcsMessage, SmsMessage]
