# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.form import Form
from ..types.form_field import FormField
from ..types.form_theme_override import FormThemeOverride
from ..types.list_forms_response import ListFormsResponse
from ..types.send_form_params import SendFormParams
from .raw_client import AsyncRawFormsClient, RawFormsClient
from .types.forms_send_response import FormsSendResponse

if typing.TYPE_CHECKING:
    from .submissions.client import AsyncSubmissionsClient, SubmissionsClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FormsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFormsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._submissions: typing.Optional[SubmissionsClient] = None

    @property
    def with_raw_response(self) -> RawFormsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFormsClient
        """
        return self._raw_client

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Form:
        """
        Retrieve a form by id. Includes submission count, last submission timestamp, and archive state.

        Parameters
        ----------
        id : str
            The unique identifier of the form you want to retrieve.
            <br><br> This identifier is a string that always begins with the prefix `form_`, for example: `form_Oy2n7iUoi9CJwUU6`. It's returned on every form response (`Form.id`) and by [`POST /forms/send`](/api-reference/forms/send-form) (`response.form.id`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Form
            The form.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.forms.get(
            id="form_Oy2n7iUoi9CJwUU6",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Sequence[FormField]] = OMIT,
        can_update: typing.Optional[bool] = OMIT,
        expires_at: typing.Optional[dt.datetime] = OMIT,
        theme_override: typing.Optional[FormThemeOverride] = OMIT,
        archived_at: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Form:
        """
        Partial update. Only keys present in the body are applied. Archived forms (non-null `archived_at`) cannot be updated — restore the form by setting `archived_at: null` in a PATCH first.

        Parameters
        ----------
        id : str
            The unique identifier of the form you want to update.
            <br><br> This identifier is a string that always begins with the prefix `form_`, for example: `form_Oy2n7iUoi9CJwUU6`.

        name : typing.Optional[str]
            Replace the form's title. Pass `null` to clear.

        description : typing.Optional[str]
            Replace the form's description. Pass `null` to clear.

        fields : typing.Optional[typing.Sequence[FormField]]
            Replace the full set of fields on the form. Partial field updates aren't supported — send the complete new list.

        can_update : typing.Optional[bool]
            Toggle whether the recipient can re-edit their submission.

        expires_at : typing.Optional[dt.datetime]
            Set or clear the form's expiration timestamp.

        theme_override : typing.Optional[FormThemeOverride]
            Replace the per-form theme override. Pass `null` to revert to team defaults.

        archived_at : typing.Optional[dt.datetime]
            Set to an ISO timestamp to archive the form (soft-delete), or `null` to restore an archived form.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Form
            Updated form.

        Examples
        --------
        import datetime

        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.forms.update(
            id="form_Oy2n7iUoi9CJwUU6",
            name="Contact request (v2)",
            can_update=True,
            expires_at=datetime.datetime.fromisoformat(
                "2026-12-31 23:59:59+00:00",
            ),
        )
        """
        _response = self._raw_client.update(
            id,
            name=name,
            description=description,
            fields=fields,
            can_update=can_update,
            expires_at=expires_at,
            theme_override=theme_override,
            archived_at=archived_at,
            request_options=request_options,
        )
        return _response.data

    def list(
        self,
        *,
        page_index: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListFormsResponse:
        """
        Paginated list of forms on your team, sorted by creation date (newest first). Includes archived forms.

        Parameters
        ----------
        page_index : typing.Optional[int]
            Zero-based page index.

        page_size : typing.Optional[int]
            Number of forms to return in a single page. Max 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFormsResponse
            Paginated list of forms.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.forms.list(
            page_index=0,
            page_size=20,
        )
        """
        _response = self._raw_client.list(page_index=page_index, page_size=page_size, request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        fields: typing.Sequence[FormField],
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        can_update: typing.Optional[bool] = OMIT,
        expires_at: typing.Optional[dt.datetime] = OMIT,
        theme_override: typing.Optional[FormThemeOverride] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Form:
        """
        Create a hosted form without sending it. <br>

        Returns the form object including its public URL — `https://forms.pinnacle.sh/{form_id}`. <br>

        To also deliver the URL to a recipient over SMS or RCS in a single call, use [`POST /forms/send`](/api-reference/forms/send-form).

        Parameters
        ----------
        fields : typing.Sequence[FormField]
            Ordered list of fields the recipient will fill out. At least one field is required.

        name : typing.Optional[str]
            Human-readable name for the form. Rendered as the form's title.

        description : typing.Optional[str]
            Longer description rendered below the title.

        can_update : typing.Optional[bool]
            If true, the recipient can reopen the submission URL and edit their answers. When false (default), the submission URL becomes read-only (`Already submitted`) after the first submit.

        expires_at : typing.Optional[dt.datetime]
            After this timestamp the form stops accepting submissions. Omit for no expiration.

        theme_override : typing.Optional[FormThemeOverride]
            Per-form theme tweaks layered on top of your team's default theme. Omit or set to null to use team defaults.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Form
            Form created.

        Examples
        --------
        from rcs import (
            FormField_Email,
            FormField_Phone,
            FormField_Select,
            FormField_Text,
            FormFieldOption,
            Pinnacle,
        )

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.forms.create(
            name="Contact request",
            description="We'll follow up over SMS or RCS.",
            fields=[
                FormField_Text(
                    key="full_name",
                    label="Full name",
                    required=True,
                    placeholder="Ada Lovelace",
                    min_length=2,
                    max_length=60,
                ),
                FormField_Email(
                    key="email",
                    label="Email",
                    required=True,
                    placeholder="you@example.com",
                ),
                FormField_Phone(
                    key="phone",
                    label="Phone",
                    required=True,
                    placeholder="(555) 555-1212",
                ),
                FormField_Select(
                    key="plan",
                    label="Plan",
                    required=True,
                    options=[
                        FormFieldOption(
                            value="basic",
                            label="Basic",
                        ),
                        FormFieldOption(
                            value="pro",
                            label="Pro",
                        ),
                        FormFieldOption(
                            value="enterprise",
                            label="Enterprise",
                        ),
                    ],
                ),
            ],
            can_update=False,
        )
        """
        _response = self._raw_client.create(
            fields=fields,
            name=name,
            description=description,
            can_update=can_update,
            expires_at=expires_at,
            theme_override=theme_override,
            request_options=request_options,
        )
        return _response.data

    def send(
        self, *, request: SendFormParams, request_options: typing.Optional[RequestOptions] = None
    ) -> FormsSendResponse:
        """
        Send a form to a recipient over SMS or RCS, or mint a standalone submission URL.

        Pass `form` as either an existing form id (`form_*`) or an inline `{ fields, ... }` definition to mint a new form for this send.

        The delivery channel is inferred from `from`:
        - `from: "agent_*"` → RCS (with optional SMS `fallback`)
        - `from: "+E.164"` → SMS

        When `to` is provided, Pinnacle dispatches a message whose body contains the submission URL and the recipient is recorded on the response: `submission.to` echoes the same E.164 number and `message_id` is the id of the outbound SMS/RCS.

        When `to` is omitted, no message is sent — `submission.to` and `message_id` are both `null` — which is useful for embedding the URL in your own outreach.

        On completion, a `FORM.SUBMISSION` webhook event is delivered to webhooks subscribed to the sender. See [Receiving Messages and User Events](/guides/messages/receiving).

        Parameters
        ----------
        request : SendFormParams

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormsSendResponse
            Form sent (or URL minted when `to` is omitted).

        Examples
        --------
        from rcs import (
            Pinnacle,
            SendFormOptions,
            SendFormViaRcsParams,
            SendFormViaRcsRequestFallback,
        )

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.forms.send(
            request=SendFormViaRcsParams(
                from_="agent_iM9wQcyBBjYn",
                to="+14155551234",
                form="form_Oy2n7iUoi9CJwUU6",
                fallback=SendFormViaRcsRequestFallback(
                    from_="+14155550000",
                ),
                options=SendFormOptions(
                    webview_mode="FULL",
                ),
            ),
        )
        """
        _response = self._raw_client.send(request=request, request_options=request_options)
        return _response.data

    @property
    def submissions(self):
        if self._submissions is None:
            from .submissions.client import SubmissionsClient  # noqa: E402

            self._submissions = SubmissionsClient(client_wrapper=self._client_wrapper)
        return self._submissions


class AsyncFormsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFormsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._submissions: typing.Optional[AsyncSubmissionsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawFormsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFormsClient
        """
        return self._raw_client

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Form:
        """
        Retrieve a form by id. Includes submission count, last submission timestamp, and archive state.

        Parameters
        ----------
        id : str
            The unique identifier of the form you want to retrieve.
            <br><br> This identifier is a string that always begins with the prefix `form_`, for example: `form_Oy2n7iUoi9CJwUU6`. It's returned on every form response (`Form.id`) and by [`POST /forms/send`](/api-reference/forms/send-form) (`response.form.id`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Form
            The form.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.forms.get(
                id="form_Oy2n7iUoi9CJwUU6",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Sequence[FormField]] = OMIT,
        can_update: typing.Optional[bool] = OMIT,
        expires_at: typing.Optional[dt.datetime] = OMIT,
        theme_override: typing.Optional[FormThemeOverride] = OMIT,
        archived_at: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Form:
        """
        Partial update. Only keys present in the body are applied. Archived forms (non-null `archived_at`) cannot be updated — restore the form by setting `archived_at: null` in a PATCH first.

        Parameters
        ----------
        id : str
            The unique identifier of the form you want to update.
            <br><br> This identifier is a string that always begins with the prefix `form_`, for example: `form_Oy2n7iUoi9CJwUU6`.

        name : typing.Optional[str]
            Replace the form's title. Pass `null` to clear.

        description : typing.Optional[str]
            Replace the form's description. Pass `null` to clear.

        fields : typing.Optional[typing.Sequence[FormField]]
            Replace the full set of fields on the form. Partial field updates aren't supported — send the complete new list.

        can_update : typing.Optional[bool]
            Toggle whether the recipient can re-edit their submission.

        expires_at : typing.Optional[dt.datetime]
            Set or clear the form's expiration timestamp.

        theme_override : typing.Optional[FormThemeOverride]
            Replace the per-form theme override. Pass `null` to revert to team defaults.

        archived_at : typing.Optional[dt.datetime]
            Set to an ISO timestamp to archive the form (soft-delete), or `null` to restore an archived form.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Form
            Updated form.

        Examples
        --------
        import asyncio
        import datetime

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.forms.update(
                id="form_Oy2n7iUoi9CJwUU6",
                name="Contact request (v2)",
                can_update=True,
                expires_at=datetime.datetime.fromisoformat(
                    "2026-12-31 23:59:59+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            name=name,
            description=description,
            fields=fields,
            can_update=can_update,
            expires_at=expires_at,
            theme_override=theme_override,
            archived_at=archived_at,
            request_options=request_options,
        )
        return _response.data

    async def list(
        self,
        *,
        page_index: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListFormsResponse:
        """
        Paginated list of forms on your team, sorted by creation date (newest first). Includes archived forms.

        Parameters
        ----------
        page_index : typing.Optional[int]
            Zero-based page index.

        page_size : typing.Optional[int]
            Number of forms to return in a single page. Max 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFormsResponse
            Paginated list of forms.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.forms.list(
                page_index=0,
                page_size=20,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            page_index=page_index, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        *,
        fields: typing.Sequence[FormField],
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        can_update: typing.Optional[bool] = OMIT,
        expires_at: typing.Optional[dt.datetime] = OMIT,
        theme_override: typing.Optional[FormThemeOverride] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Form:
        """
        Create a hosted form without sending it. <br>

        Returns the form object including its public URL — `https://forms.pinnacle.sh/{form_id}`. <br>

        To also deliver the URL to a recipient over SMS or RCS in a single call, use [`POST /forms/send`](/api-reference/forms/send-form).

        Parameters
        ----------
        fields : typing.Sequence[FormField]
            Ordered list of fields the recipient will fill out. At least one field is required.

        name : typing.Optional[str]
            Human-readable name for the form. Rendered as the form's title.

        description : typing.Optional[str]
            Longer description rendered below the title.

        can_update : typing.Optional[bool]
            If true, the recipient can reopen the submission URL and edit their answers. When false (default), the submission URL becomes read-only (`Already submitted`) after the first submit.

        expires_at : typing.Optional[dt.datetime]
            After this timestamp the form stops accepting submissions. Omit for no expiration.

        theme_override : typing.Optional[FormThemeOverride]
            Per-form theme tweaks layered on top of your team's default theme. Omit or set to null to use team defaults.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Form
            Form created.

        Examples
        --------
        import asyncio

        from rcs import (
            AsyncPinnacle,
            FormField_Email,
            FormField_Phone,
            FormField_Select,
            FormField_Text,
            FormFieldOption,
        )

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.forms.create(
                name="Contact request",
                description="We'll follow up over SMS or RCS.",
                fields=[
                    FormField_Text(
                        key="full_name",
                        label="Full name",
                        required=True,
                        placeholder="Ada Lovelace",
                        min_length=2,
                        max_length=60,
                    ),
                    FormField_Email(
                        key="email",
                        label="Email",
                        required=True,
                        placeholder="you@example.com",
                    ),
                    FormField_Phone(
                        key="phone",
                        label="Phone",
                        required=True,
                        placeholder="(555) 555-1212",
                    ),
                    FormField_Select(
                        key="plan",
                        label="Plan",
                        required=True,
                        options=[
                            FormFieldOption(
                                value="basic",
                                label="Basic",
                            ),
                            FormFieldOption(
                                value="pro",
                                label="Pro",
                            ),
                            FormFieldOption(
                                value="enterprise",
                                label="Enterprise",
                            ),
                        ],
                    ),
                ],
                can_update=False,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            fields=fields,
            name=name,
            description=description,
            can_update=can_update,
            expires_at=expires_at,
            theme_override=theme_override,
            request_options=request_options,
        )
        return _response.data

    async def send(
        self, *, request: SendFormParams, request_options: typing.Optional[RequestOptions] = None
    ) -> FormsSendResponse:
        """
        Send a form to a recipient over SMS or RCS, or mint a standalone submission URL.

        Pass `form` as either an existing form id (`form_*`) or an inline `{ fields, ... }` definition to mint a new form for this send.

        The delivery channel is inferred from `from`:
        - `from: "agent_*"` → RCS (with optional SMS `fallback`)
        - `from: "+E.164"` → SMS

        When `to` is provided, Pinnacle dispatches a message whose body contains the submission URL and the recipient is recorded on the response: `submission.to` echoes the same E.164 number and `message_id` is the id of the outbound SMS/RCS.

        When `to` is omitted, no message is sent — `submission.to` and `message_id` are both `null` — which is useful for embedding the URL in your own outreach.

        On completion, a `FORM.SUBMISSION` webhook event is delivered to webhooks subscribed to the sender. See [Receiving Messages and User Events](/guides/messages/receiving).

        Parameters
        ----------
        request : SendFormParams

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormsSendResponse
            Form sent (or URL minted when `to` is omitted).

        Examples
        --------
        import asyncio

        from rcs import (
            AsyncPinnacle,
            SendFormOptions,
            SendFormViaRcsParams,
            SendFormViaRcsRequestFallback,
        )

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.forms.send(
                request=SendFormViaRcsParams(
                    from_="agent_iM9wQcyBBjYn",
                    to="+14155551234",
                    form="form_Oy2n7iUoi9CJwUU6",
                    fallback=SendFormViaRcsRequestFallback(
                        from_="+14155550000",
                    ),
                    options=SendFormOptions(
                        webview_mode="FULL",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send(request=request, request_options=request_options)
        return _response.data

    @property
    def submissions(self):
        if self._submissions is None:
            from .submissions.client import AsyncSubmissionsClient  # noqa: E402

            self._submissions = AsyncSubmissionsClient(client_wrapper=self._client_wrapper)
        return self._submissions
