# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.list_network_requests_response import ListNetworkRequestsResponse
from ...types.network_request_id import NetworkRequestId
from ...types.network_request_status import NetworkRequestStatus
from ...types.network_request_summary import NetworkRequestSummary
from ...types.network_request_type import NetworkRequestType
from .raw_client import AsyncRawRequestsClient, RawRequestsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RequestsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRequestsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRequestsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRequestsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        page_index: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        type: typing.Optional[NetworkRequestType] = OMIT,
        status: typing.Optional[NetworkRequestStatus] = OMIT,
        client_ref: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListNetworkRequestsResponse:
        """
        List Network API request records for your team, sorted newest first. Use filters to audit recent checks by type, status, or your own `clientRef`.

        <Note>
          Limited availability. Contact [founders@pinnacle.sh](mailto:founders@pinnacle.sh) to request access.
        </Note>

        Parameters
        ----------
        page_index : typing.Optional[int]
            Zero-based page index. Use 0 for the first page.

        page_size : typing.Optional[int]
            Number of records to return, from 1 to 100.

        type : typing.Optional[NetworkRequestType]

        status : typing.Optional[NetworkRequestStatus]

        client_ref : typing.Optional[str]
            Filter by your correlation ID. Must be 1 to 40 characters when provided.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListNetworkRequestsResponse
            Returns a paginated list of Network API request summaries.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.network.requests.list(
            page_index=0,
            page_size=20,
            type="silent-auth",
            status="completed",
            client_ref="user_123",
        )
        """
        _response = self._raw_client.list(
            page_index=page_index,
            page_size=page_size,
            type=type,
            status=status,
            client_ref=client_ref,
            request_options=request_options,
        )
        return _response.data

    def get(
        self, request_id: NetworkRequestId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> NetworkRequestSummary:
        """
        Retrieve one Network API request by ID. The response includes lifecycle timestamps, request status, your `clientRef`, and result fields from the original check.

        <Note>
          Limited availability. Contact [founders@pinnacle.sh](mailto:founders@pinnacle.sh) to request access.
        </Note>

        Parameters
        ----------
        request_id : NetworkRequestId
            Network API request ID returned by a Network API endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        NetworkRequestSummary
            Returns the Network API request summary.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.network.requests.get(
            request_id="nar_1234567890ABCDEF",
        )
        """
        _response = self._raw_client.get(request_id, request_options=request_options)
        return _response.data


class AsyncRequestsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRequestsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRequestsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRequestsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        page_index: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        type: typing.Optional[NetworkRequestType] = OMIT,
        status: typing.Optional[NetworkRequestStatus] = OMIT,
        client_ref: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListNetworkRequestsResponse:
        """
        List Network API request records for your team, sorted newest first. Use filters to audit recent checks by type, status, or your own `clientRef`.

        <Note>
          Limited availability. Contact [founders@pinnacle.sh](mailto:founders@pinnacle.sh) to request access.
        </Note>

        Parameters
        ----------
        page_index : typing.Optional[int]
            Zero-based page index. Use 0 for the first page.

        page_size : typing.Optional[int]
            Number of records to return, from 1 to 100.

        type : typing.Optional[NetworkRequestType]

        status : typing.Optional[NetworkRequestStatus]

        client_ref : typing.Optional[str]
            Filter by your correlation ID. Must be 1 to 40 characters when provided.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListNetworkRequestsResponse
            Returns a paginated list of Network API request summaries.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.network.requests.list(
                page_index=0,
                page_size=20,
                type="silent-auth",
                status="completed",
                client_ref="user_123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            page_index=page_index,
            page_size=page_size,
            type=type,
            status=status,
            client_ref=client_ref,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self, request_id: NetworkRequestId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> NetworkRequestSummary:
        """
        Retrieve one Network API request by ID. The response includes lifecycle timestamps, request status, your `clientRef`, and result fields from the original check.

        <Note>
          Limited availability. Contact [founders@pinnacle.sh](mailto:founders@pinnacle.sh) to request access.
        </Note>

        Parameters
        ----------
        request_id : NetworkRequestId
            Network API request ID returned by a Network API endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        NetworkRequestSummary
            Returns the Network API request summary.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.network.requests.get(
                request_id="nar_1234567890ABCDEF",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(request_id, request_options=request_options)
        return _response.data
