# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.call import Call
from ..types.call_direction import CallDirection
from ..types.call_metadata import CallMetadata
from ..types.call_state import CallState
from ..types.call_stream_token import CallStreamToken
from ..types.created_call import CreatedCall
from ..types.list_call_events_response import ListCallEventsResponse
from ..types.list_calls_response import ListCallsResponse
from ..types.recording_download import RecordingDownload
from .raw_client import AsyncRawCallsClient, RawCallsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CallsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCallsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        state: typing.Optional[CallState] = None,
        direction: typing.Optional[CallDirection] = None,
        from_: typing.Optional[str] = None,
        to: typing.Optional[str] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCallsResponse:
        """
        List voice calls for your team. Results are sorted newest first.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum calls to return.

        cursor : typing.Optional[str]
            Opaque cursor returned by the previous page.

        state : typing.Optional[CallState]

        direction : typing.Optional[CallDirection]

        from_ : typing.Optional[str]

        to : typing.Optional[str]

        created_after : typing.Optional[dt.datetime]

        created_before : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCallsResponse
            Calls page.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.calls.list()
        """
        _response = self._raw_client.list(
            limit=limit,
            cursor=cursor,
            state=state,
            direction=direction,
            from_=from_,
            to=to,
            created_after=created_after,
            created_before=created_before,
            request_options=request_options,
        )
        return _response.data

    def create(
        self,
        *,
        to: str,
        from_: str,
        record: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[CallMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatedCall:
        """
        Start an outbound voice call from a voice-enabled phone number owned by your team.

        Parameters
        ----------
        to : str
            Destination phone number in E.164 format.

        from_ : str
            Voice-enabled phone number owned by your team.

        record : typing.Optional[bool]
            Start recording as soon as the call stream connects.

        metadata : typing.Optional[CallMetadata]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatedCall
            Call created.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.calls.create(
            to="to",
            from_="from",
        )
        """
        _response = self._raw_client.create(
            to=to, from_=from_, record=record, metadata=metadata, request_options=request_options
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Call:
        """
        Retrieve one voice call by its Pinnacle call ID.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Call
            Call details.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.calls.get(
            id="call_7cQe4F8xT1yB2mN9pK3L",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def cancel(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Call:
        """
        End a live call. Terminal calls are returned unchanged.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Call
            Canceled call.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.calls.cancel(
            id="call_7cQe4F8xT1yB2mN9pK3L",
        )
        """
        _response = self._raw_client.cancel(id, request_options=request_options)
        return _response.data

    def update(
        self, id: str, *, metadata: CallMetadata, request_options: typing.Optional[RequestOptions] = None
    ) -> Call:
        """
        Replace a call's metadata. For live calls, future call events carry the updated metadata.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        metadata : CallMetadata

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Call
            Updated call.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.calls.update(
            id="call_7cQe4F8xT1yB2mN9pK3L",
            metadata={"key": "value"},
        )
        """
        _response = self._raw_client.update(id, metadata=metadata, request_options=request_options)
        return _response.data

    def list_events(
        self,
        id: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCallEventsResponse:
        """
        List the event timeline for a call.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        limit : typing.Optional[int]
            Maximum call events to return.

        cursor : typing.Optional[str]
            Opaque cursor returned by the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCallEventsResponse
            Call events page.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.calls.list_events(
            id="call_7cQe4F8xT1yB2mN9pK3L",
        )
        """
        _response = self._raw_client.list_events(id, limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    def create_stream_token(
        self,
        id: str,
        *,
        commands_enabled: typing.Optional[bool] = OMIT,
        stream_id: typing.Optional[str] = OMIT,
        record: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CallStreamToken:
        """
        Mint a short-lived WebSocket token for a call. Use the returned `stream_url` to connect to Pinnacle's bidirectional voice stream.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        commands_enabled : typing.Optional[bool]
            Whether this WebSocket may send call commands. Defaults to true.

        stream_id : typing.Optional[str]
            Customer-chosen stream ID for reconnects and multiple subscribers.

        record : typing.Optional[bool]
            Enable recording for this WebSocket stream.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallStreamToken
            Stream token.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.calls.create_stream_token(
            id="call_7cQe4F8xT1yB2mN9pK3L",
        )
        """
        _response = self._raw_client.create_stream_token(
            id, commands_enabled=commands_enabled, stream_id=stream_id, record=record, request_options=request_options
        )
        return _response.data

    def download_recording(
        self,
        id: str,
        *,
        expires_in: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecordingDownload:
        """
        Return a short-lived signed URL for the call recording.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        expires_in : typing.Optional[int]
            Signed URL lifetime in seconds. Defaults to 300 and may be at most 86400.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordingDownload
            Recording download URL.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.calls.download_recording(
            id="call_7cQe4F8xT1yB2mN9pK3L",
        )
        """
        _response = self._raw_client.download_recording(id, expires_in=expires_in, request_options=request_options)
        return _response.data

    def delete_recording(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete the canonical recording and queued fragments for a terminal call.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.calls.delete_recording(
            id="call_7cQe4F8xT1yB2mN9pK3L",
        )
        """
        _response = self._raw_client.delete_recording(id, request_options=request_options)
        return _response.data


class AsyncCallsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCallsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        state: typing.Optional[CallState] = None,
        direction: typing.Optional[CallDirection] = None,
        from_: typing.Optional[str] = None,
        to: typing.Optional[str] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCallsResponse:
        """
        List voice calls for your team. Results are sorted newest first.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum calls to return.

        cursor : typing.Optional[str]
            Opaque cursor returned by the previous page.

        state : typing.Optional[CallState]

        direction : typing.Optional[CallDirection]

        from_ : typing.Optional[str]

        to : typing.Optional[str]

        created_after : typing.Optional[dt.datetime]

        created_before : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCallsResponse
            Calls page.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.calls.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            limit=limit,
            cursor=cursor,
            state=state,
            direction=direction,
            from_=from_,
            to=to,
            created_after=created_after,
            created_before=created_before,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self,
        *,
        to: str,
        from_: str,
        record: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[CallMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatedCall:
        """
        Start an outbound voice call from a voice-enabled phone number owned by your team.

        Parameters
        ----------
        to : str
            Destination phone number in E.164 format.

        from_ : str
            Voice-enabled phone number owned by your team.

        record : typing.Optional[bool]
            Start recording as soon as the call stream connects.

        metadata : typing.Optional[CallMetadata]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatedCall
            Call created.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.calls.create(
                to="to",
                from_="from",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            to=to, from_=from_, record=record, metadata=metadata, request_options=request_options
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Call:
        """
        Retrieve one voice call by its Pinnacle call ID.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Call
            Call details.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.calls.get(
                id="call_7cQe4F8xT1yB2mN9pK3L",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def cancel(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Call:
        """
        End a live call. Terminal calls are returned unchanged.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Call
            Canceled call.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.calls.cancel(
                id="call_7cQe4F8xT1yB2mN9pK3L",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(id, request_options=request_options)
        return _response.data

    async def update(
        self, id: str, *, metadata: CallMetadata, request_options: typing.Optional[RequestOptions] = None
    ) -> Call:
        """
        Replace a call's metadata. For live calls, future call events carry the updated metadata.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        metadata : CallMetadata

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Call
            Updated call.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.calls.update(
                id="call_7cQe4F8xT1yB2mN9pK3L",
                metadata={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(id, metadata=metadata, request_options=request_options)
        return _response.data

    async def list_events(
        self,
        id: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCallEventsResponse:
        """
        List the event timeline for a call.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        limit : typing.Optional[int]
            Maximum call events to return.

        cursor : typing.Optional[str]
            Opaque cursor returned by the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCallEventsResponse
            Call events page.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.calls.list_events(
                id="call_7cQe4F8xT1yB2mN9pK3L",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_events(id, limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    async def create_stream_token(
        self,
        id: str,
        *,
        commands_enabled: typing.Optional[bool] = OMIT,
        stream_id: typing.Optional[str] = OMIT,
        record: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CallStreamToken:
        """
        Mint a short-lived WebSocket token for a call. Use the returned `stream_url` to connect to Pinnacle's bidirectional voice stream.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        commands_enabled : typing.Optional[bool]
            Whether this WebSocket may send call commands. Defaults to true.

        stream_id : typing.Optional[str]
            Customer-chosen stream ID for reconnects and multiple subscribers.

        record : typing.Optional[bool]
            Enable recording for this WebSocket stream.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallStreamToken
            Stream token.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.calls.create_stream_token(
                id="call_7cQe4F8xT1yB2mN9pK3L",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_stream_token(
            id, commands_enabled=commands_enabled, stream_id=stream_id, record=record, request_options=request_options
        )
        return _response.data

    async def download_recording(
        self,
        id: str,
        *,
        expires_in: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecordingDownload:
        """
        Return a short-lived signed URL for the call recording.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        expires_in : typing.Optional[int]
            Signed URL lifetime in seconds. Defaults to 300 and may be at most 86400.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordingDownload
            Recording download URL.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.calls.download_recording(
                id="call_7cQe4F8xT1yB2mN9pK3L",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.download_recording(
            id, expires_in=expires_in, request_options=request_options
        )
        return _response.data

    async def delete_recording(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete the canonical recording and queued fragments for a terminal call.

        Parameters
        ----------
        id : str
            Pinnacle call ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.calls.delete_recording(
                id="call_7cQe4F8xT1yB2mN9pK3L",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_recording(id, request_options=request_options)
        return _response.data
