# This file was auto-generated by Fern from our API Definition.

import typing

from ....types.scheduled_message import ScheduledMessage
from ....types.sent_rich_message import SentRichMessage
from ....types.sent_rich_message_fallback_mms import SentRichMessageFallbackMms
from ....types.sent_rich_message_fallback_sms import SentRichMessageFallbackSms

SendRichMessageResponse = typing.Union[
    SentRichMessage, ScheduledMessage, SentRichMessageFallbackSms, SentRichMessageFallbackMms
]
