# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.simulate_user_params import SimulateUserParams
from ...types.simulate_user_response import SimulateUserResponse
from .raw_client import AsyncRawSimulateClient, RawSimulateClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SimulateClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSimulateClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSimulateClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSimulateClient
        """
        return self._raw_client

    def user(
        self, *, request: SimulateUserParams, request_options: typing.Optional[RequestOptions] = None
    ) -> SimulateUserResponse:
        """
        Simulate inbound messages and button presses from a user.

        Parameters
        ----------
        request : SimulateUserParams

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SimulateUserResponse
            Returns simulation result.

        Examples
        --------
        from rcs import Pinnacle, SimulateMessageInput, SimulateUserMessage

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.messages.simulate.user(
            request=SimulateUserMessage(
                from_="+14155551234",
                to="+14155555678",
                message=SimulateMessageInput(
                    text="Hello from the test user!",
                ),
            ),
        )
        """
        _response = self._raw_client.user(request=request, request_options=request_options)
        return _response.data


class AsyncSimulateClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSimulateClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSimulateClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSimulateClient
        """
        return self._raw_client

    async def user(
        self, *, request: SimulateUserParams, request_options: typing.Optional[RequestOptions] = None
    ) -> SimulateUserResponse:
        """
        Simulate inbound messages and button presses from a user.

        Parameters
        ----------
        request : SimulateUserParams

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SimulateUserResponse
            Returns simulation result.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle, SimulateMessageInput, SimulateUserMessage

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.messages.simulate.user(
                request=SimulateUserMessage(
                    from_="+14155551234",
                    to="+14155555678",
                    message=SimulateMessageInput(
                        text="Hello from the test user!",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.user(request=request, request_options=request_options)
        return _response.data
