# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.scheduled_form_send_result import ScheduledFormSendResult
from ...types.send_form_result import SendFormResult

FormsSendResponse = typing.Union[SendFormResult, ScheduledFormSendResult]
