# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentWebsiteEntry(UniversalBaseModel):
    """
    A website contact entry for the RCS agent's contact information.
    """

    url: str = pydantic.Field()
    """
    A valid URL for the website.
    """

    label: str = pydantic.Field()
    """
    Display label for the website (e.g., "Website", "Help Center").
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
