# This file was auto-generated by Fern from our API Definition.

import typing

AgentSummaryConfigAgentUseCase = typing.Union[
    typing.Literal["TRANSACTIONAL", "PROMOTIONAL", "OTP", "MULTI_USE"], typing.Any
]
