# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .call_direction import CallDirection
from .call_state import CallState
from .recording_state import RecordingState


class Call(UniversalBaseModel):
    id: str
    state: CallState
    direction: CallDirection
    to: typing.Optional[str] = None
    from_: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="from")] = None
    created_at: dt.datetime
    started_at: typing.Optional[dt.datetime] = None
    answered_at: typing.Optional[dt.datetime] = None
    ended_at: typing.Optional[dt.datetime] = None
    metadata: typing.Dict[str, str]
    recording_state: typing.Optional[RecordingState] = None
    hangup_cause: typing.Optional[str] = None
    record: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Present on create responses and echoes the requested create-time recording option.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
