# This file was auto-generated by Fern from our API Definition.

import typing

CallState = typing.Union[
    typing.Literal["INITIATED", "RINGING", "ANSWERED", "BRIDGED", "ENDED", "FAILED", "NO_ANSWER", "BUSY", "CANCELED"],
    typing.Any,
]
