# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CampaignStatusEventAgent(UniversalBaseModel):
    """
    The RCS agent the campaign-status update is for.
    """

    id: str = pydantic.Field()
    """
    RCS agent id (`agent_*`).
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name configured on the agent. Null if unset.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
