# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .verification_status import VerificationStatus


class CampaignStatusEventCarrierLaunchesVerification(UniversalBaseModel):
    """
    External verifier status. AEGIS (the U.S. carrier vetting
    authority used by AT&T, T-Mobile, and Verizon) and Google each
    send a verification email to the brand's contact address. Each
    verifier moves through `NOT_SENT` → `SENT` → `VERIFIED` once
    the brand replies and the verifier confirms ownership.
    """

    aegis: typing_extensions.Annotated[VerificationStatus, FieldMetadata(alias="AEGIS")]
    google: typing_extensions.Annotated[VerificationStatus, FieldMetadata(alias="GOOGLE")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
