# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CampaignStatusEventBrand(UniversalBaseModel):
    """
    Reference to the brand owning the agent's connected campaign.
    """

    public_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="publicId")] = pydantic.Field(
        default=None
    )
    """
    Brand public id (`b_*`). Null if no brand is linked.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Brand display name. Null if unset.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
