# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .carrier_launch_status import CarrierLaunchStatus


class CarrierLaunchesCarriers(UniversalBaseModel):
    """
    Per-carrier launch status. Each carrier moves through
    `NOT_LAUNCHED` → `PENDING` → `LAUNCHED` as Pinnacle submits the
    agent for review and the carrier accepts it. The agent is only
    deliverable on a carrier once that carrier reports `LAUNCHED`.
    """

    att: typing_extensions.Annotated[CarrierLaunchStatus, FieldMetadata(alias="ATT")] = pydantic.Field()
    """
    AT&T launch status.
    """

    tmobile: typing_extensions.Annotated[CarrierLaunchStatus, FieldMetadata(alias="TMOBILE")] = pydantic.Field()
    """
    T-Mobile launch status.
    """

    verizon: typing_extensions.Annotated[CarrierLaunchStatus, FieldMetadata(alias="VERIZON")] = pydantic.Field()
    """
    Verizon launch status.
    """

    others: typing_extensions.Annotated[CarrierLaunchStatus, FieldMetadata(alias="OTHERS")] = pydantic.Field()
    """
    Other carriers launch status.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
