# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .field_base import FieldBase
from .form_field_option import FormFieldOption


class CheckboxField(FieldBase):
    """
    Multi-select checkbox group when `options` is provided. If `options` is omitted the field renders as a single boolean checkbox.
    """

    options: typing.Optional[typing.List[FormFieldOption]] = pydantic.Field(default=None)
    """
    Choices shown as checkboxes. Omit to render a single boolean checkbox.
    """

    min_selected: typing.Optional[int] = pydantic.Field(default=None)
    """
    Minimum number of boxes the submitter must check.
    """

    max_selected: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum number of boxes the submitter may check. Extra boxes become uninteractive once the cap is reached.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
