# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .field_base import FieldBase


class DatetimeField(FieldBase):
    """
    Local-datetime picker. `min`/`max` accept ISO 8601 timestamps.
    """

    placeholder: typing.Optional[str] = pydantic.Field(default=None)
    """
    Ghost text shown inside the input while it's empty.
    """

    min: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Earliest selectable instant as an ISO 8601 timestamp.
    """

    max: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Latest selectable instant as an ISO 8601 timestamp.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
