# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .fax_billing_status_enum import FaxBillingStatusEnum
from .fax_direction_enum import FaxDirectionEnum
from .fax_failure_reason_enum import FaxFailureReasonEnum
from .fax_status_enum import FaxStatusEnum


class Fax(UniversalBaseModel):
    id: str
    direction: FaxDirectionEnum
    from_: typing_extensions.Annotated[str, FieldMetadata(alias="from")] = pydantic.Field()
    """
    Sender number in E.164 format.
    """

    to: str = pydantic.Field()
    """
    Recipient number in E.164 format.
    """

    status: FaxStatusEnum
    pages: int = pydantic.Field()
    """
    Transmitted page count across the fax. This can be zero before transmission and can include only transmitted pages after a partial failure. Outbound documents can contain at most 3,500 pages.
    """

    duration_seconds: typing_extensions.Annotated[float, FieldMetadata(alias="durationSeconds")] = pydantic.Field()
    """
    Total transmission duration in seconds.
    """

    partial_content: typing_extensions.Annotated[bool, FieldMetadata(alias="partialContent")] = pydantic.Field()
    """
    Whether only part of the document was delivered, including when an earlier part succeeded before a later part failed.
    """

    failure_reason: typing_extensions.Annotated[
        typing.Optional[FaxFailureReasonEnum], FieldMetadata(alias="failureReason")
    ] = None
    cost: float = pydantic.Field()
    """
    Settled fax cost in USD, calculated at $0.025 per final transmitted page. Quality does not change the rate.
    """

    reserved_cost: typing_extensions.Annotated[float, FieldMetadata(alias="reservedCost")] = pydantic.Field()
    """
    Credit reserved after document preparation for an unsettled outbound fax, in USD. This equals $0.025 multiplied by the prepared page count, regardless of quality, and is zero while status is `PREPARING`.
    """

    billing_status: typing_extensions.Annotated[FaxBillingStatusEnum, FieldMetadata(alias="billingStatus")] = (
        pydantic.Field()
    )
    """
    `PENDING` while a reservation or uncertain submission remains open; `SETTLED` after final charging, refund, or cancellation.
    """

    has_media: typing_extensions.Annotated[bool, FieldMetadata(alias="hasMedia")] = pydantic.Field()
    """
    Whether Pinnacle has archived the fax document.
    """

    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")]
    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
