# This file was auto-generated by Fern from our API Definition.

import typing

FaxFailureReasonEnum = typing.Union[
    typing.Literal[
        "MEDIA_PREPARATION_FAILED",
        "MEDIA_PREPARATION_INTERRUPTED",
        "INSUFFICIENT_CREDITS",
        "SUBMISSION_UNCONFIRMED",
        "SUBMISSION_REJECTED",
        "DELIVERY_FAILED",
    ],
    typing.Any,
]
