# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .fax import Fax
from .fax_event_type import FaxEventType


class FaxEvent(UniversalBaseModel):
    """
    Fax webhook notification. `FAX.STATUS` reports lifecycle changes, and `FAX.RECEIVED` means an inbound fax is ready.

    Webhooks intentionally omit `mediaUrl`. When `fax.hasMedia` is true, call the authenticated `GET /fax/{fax.id}` endpoint to receive a signed document URL that expires after one hour. Treat the URL as sensitive: do not log or store it, and request a new one after it expires.
    """

    id: str = pydantic.Field()
    """
    Stable event ID. Deduplicate retries using this value.
    """

    type: FaxEventType
    fax: Fax

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
