# This file was auto-generated by Fern from our API Definition.

import typing

FaxStatusEnum = typing.Union[
    typing.Literal[
        "PREPARING",
        "SUBMITTING",
        "SUBMISSION_UNKNOWN",
        "QUEUED",
        "PROCESSING",
        "SENDING",
        "RECEIVING",
        "DELIVERED",
        "RECEIVED",
        "FAILED",
        "CANCELLED",
    ],
    typing.Any,
]
