# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .form_field import FormField
from .form_theme_override import FormThemeOverride


class FormDefinition(UniversalBaseModel):
    """
    The minimum shape needed to create a form. Used by `POST /forms` and inline by `POST /forms/send`.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable name for the form. Rendered as the form's title.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Longer description rendered below the title.
    """

    fields: typing.List[FormField] = pydantic.Field()
    """
    Ordered list of fields the recipient will fill out. At least one field is required.
    """

    can_update: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, the recipient can reopen the submission URL and edit their answers. When false (default), the submission URL becomes read-only (`Already submitted`) after the first submit.
    """

    expires_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    After this timestamp the form stops accepting submissions. Omit for no expiration.
    """

    theme_override: typing.Optional[FormThemeOverride] = pydantic.Field(default=None)
    """
    Per-form theme tweaks layered on top of your team's default theme. Omit or set to null to use team defaults.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
