# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FormBackgroundImage(UniversalBaseModel):
    """
    Image background. The image is tiled or scaled across the page with optional blur and dark tint overlay.
    """

    url: str = pydantic.Field()
    """
    HTTPS URL of the background image. Must start with `https://`.
    """

    tint_opacity: int = pydantic.Field()
    """
    Darkening overlay intensity from 0 (no overlay) to 80 (heavy). Helps preserve text contrast over busy images.
    """

    blur: bool = pydantic.Field()
    """
    When true, blurs the background image.
    """

    zoom: int = pydantic.Field()
    """
    Scale percentage. 100 is native size; higher values crop the image tighter.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
