# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FormColorPalette(UniversalBaseModel):
    """
    Per-mode palette. All three colors are optional; any you omit fall back to the team default for that mode.
    """

    primary: typing.Optional[str] = pydantic.Field(default=None)
    """
    Accent color used for the submit button, focus rings, filled checkboxes, and other interactive surfaces.
    """

    background: typing.Optional[str] = pydantic.Field(default=None)
    """
    Page background color. Fallback solid color used by Safari chrome tinting and safe-area regions.
    """

    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Body text and label color.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
