# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .form_background_pattern_preset import FormBackgroundPatternPreset
from .form_gradient import FormGradient


class FormBackground_Solid(UniversalBaseModel):
    """
    Background layer for the form page. Discriminated by `type`.
    """

    type: typing.Literal["solid"] = "solid"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class FormBackground_Gradient(UniversalBaseModel):
    """
    Background layer for the form page. Discriminated by `type`.
    """

    type: typing.Literal["gradient"] = "gradient"
    light: FormGradient
    dark: FormGradient

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class FormBackground_Image(UniversalBaseModel):
    """
    Background layer for the form page. Discriminated by `type`.
    """

    type: typing.Literal["image"] = "image"
    url: str
    tint_opacity: int
    blur: bool
    zoom: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class FormBackground_Pattern(UniversalBaseModel):
    """
    Background layer for the form page. Discriminated by `type`.
    """

    type: typing.Literal["pattern"] = "pattern"
    preset: FormBackgroundPatternPreset

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


FormBackground = typing.Union[
    FormBackground_Solid, FormBackground_Gradient, FormBackground_Image, FormBackground_Pattern
]
