# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .form_color_palette import FormColorPalette


class FormThemeOverrideColors(UniversalBaseModel):
    """
    Per-mode palette overrides. Each mode is an object with optional `primary`, `background`, and `text` hex colors. Omit a mode to inherit the team default for it.
    """

    light: typing.Optional[FormColorPalette] = pydantic.Field(default=None)
    """
    Palette used when the form renders in light mode.
    """

    dark: typing.Optional[FormColorPalette] = pydantic.Field(default=None)
    """
    Palette used when the form renders in dark mode.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
