# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .form_field import FormField
from .form_theme_override import FormThemeOverride


class Form(UniversalBaseModel):
    """
    A hosted form definition.
    """

    id: str = pydantic.Field()
    """
    Form id (starts with `form_`).
    """

    url: str = pydantic.Field()
    """
    Public shareable URL of the form (`https://forms.pinnacle.sh/{form_id}`).
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable name for the form. Rendered as the form's title.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Longer description rendered below the title.
    """

    fields: typing.List[FormField] = pydantic.Field()
    """
    Ordered list of fields the recipient fills out.
    """

    can_update: bool = pydantic.Field()
    """
    When true, the recipient can reopen the submission URL and edit their answers. When false, the URL becomes read-only after the first submit.
    """

    expires_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    After this timestamp the form stops accepting submissions. Null means no expiration.
    """

    theme_override: typing.Optional[FormThemeOverride] = pydantic.Field(default=None)
    """
    Per-form theme tweaks layered on top of your team's default theme. Null means the team defaults are used as-is.
    """

    submission_count: int = pydantic.Field()
    """
    Count of distinct completed submissions for this form. Does not increment on edits to an existing `can_update=true` submission.
    """

    last_submitted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Timestamp of the most recent submission event. Updated on each new submit and on each edit of a `can_update=true` submission.
    """

    archived_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When set, the form is archived (soft-deleted) and cannot accept new submissions or be updated. Restore by PATCHing `archived_at` back to null.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    ISO 8601 timestamp of when the form was created.
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    ISO 8601 timestamp of the most recent form mutation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
