# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .form_gradient import FormGradient


class FormBackgroundGradient(UniversalBaseModel):
    """
    Two-stop linear gradient. Supply separate light- and dark-mode gradients; the renderer picks based on `theme_mode`.
    """

    light: FormGradient = pydantic.Field()
    """
    Gradient used when the form renders in light mode.
    """

    dark: FormGradient = pydantic.Field()
    """
    Gradient used when the form renders in dark mode.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
