# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .form_gradient_angle import FormGradientAngle


class FormGradient(UniversalBaseModel):
    """
    A single light- or dark-mode gradient stop pair.
    """

    from_: typing_extensions.Annotated[str, FieldMetadata(alias="from")] = pydantic.Field()
    """
    Starting color of the gradient.
    """

    to: str = pydantic.Field()
    """
    Ending color of the gradient.
    """

    angle: FormGradientAngle = pydantic.Field()
    """
    Direction the gradient runs. `top-bottom` is vertical; `diagonal` runs top-left → bottom-right.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
