# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .form_submission import FormSubmission


class ListFormSubmissionsResponse(UniversalBaseModel):
    """
    Paginated page of submissions for a form.
    """

    data: typing.List[FormSubmission] = pydantic.Field()
    """
    Submissions on this page, newest first.
    """

    has_more: typing_extensions.Annotated[bool, FieldMetadata(alias="hasMore")] = pydantic.Field()
    """
    True if there are more pages after this one. Fetch the next page by incrementing `pageIndex`.
    """

    count: int = pydantic.Field()
    """
    Number of submissions returned in `data`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
