# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .toll_free_campaign_summary import TollFreeCampaignSummary


class ListTollFreeCampaignsResponse(UniversalBaseModel):
    data: typing.List[TollFreeCampaignSummary]
    has_more: typing_extensions.Annotated[bool, FieldMetadata(alias="hasMore")]
    count: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
