# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .fax import Fax


class ListFaxesResponse(UniversalBaseModel):
    data: typing.List[Fax]
    next_offset: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="nextOffset")] = pydantic.Field(
        default=None
    )
    """
    Offset for the next page, or null when no more records exist.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
