# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .message_event_fallback_message_type import MessageEventFallbackMessageType


class MessageEventFallbackMessage(UniversalBaseModel):
    """
    Details of the fallback SMS/MMS message that was sent instead of the original RCS message.

    This field is only present when the message `status` is `FALLBACK_SENT`, indicating the original RCS message could not be delivered and a fallback message was sent instead.

    Use this information to track which fallback messages were sent and their content.
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the fallback message. This identifier is a string that always begins with the prefix `msg_`, for example: `msg_1234567890`. <br><br>
    To get the full message details, use the [GET /messages/{id}](/api-reference/messages/get) endpoint.
    """

    type: MessageEventFallbackMessageType = pydantic.Field()
    """
    Type of the fallback message sent.
    """

    from_: typing_extensions.Annotated[str, FieldMetadata(alias="from")] = pydantic.Field()
    """
    Phone number the fallback message was sent from in E.164 format.
    """

    to: str = pydantic.Field()
    """
    Recipient's phone number in E.164 format.
    """

    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Text content of the fallback message.
    """

    media_urls: typing_extensions.Annotated[typing.Optional[typing.List[str]], FieldMetadata(alias="mediaUrls")] = (
        pydantic.Field(default=None)
    )
    """
    Media URLs included in the fallback MMS message. Empty array for SMS fallbacks.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
