# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .network_request_id import NetworkRequestId
from .network_request_result import NetworkRequestResult
from .network_request_status import NetworkRequestStatus
from .network_request_type import NetworkRequestType


class NetworkRequestSummary(UniversalBaseModel):
    request_id: typing_extensions.Annotated[NetworkRequestId, FieldMetadata(alias="requestId")]
    type: NetworkRequestType
    status: NetworkRequestStatus
    client_ref: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="clientRef")] = pydantic.Field(
        default=None
    )
    """
    Your correlation ID from the original request.
    """

    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")] = pydantic.Field()
    """
    Timestamp when the request record was created.
    """

    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")] = pydantic.Field()
    """
    Timestamp when the request record was last updated.
    """

    completed_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="completedAt")] = (
        pydantic.Field(default=None)
    )
    """
    Timestamp when the request reached a terminal state.
    """

    expires_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="expiresAt")] = (
        pydantic.Field(default=None)
    )
    """
    Expiration timestamp for short-lived request flows, when applicable.
    """

    error_message: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="errorMessage")] = (
        pydantic.Field(default=None)
    )
    """
    Error message for failed requests.
    """

    result: typing.Optional[NetworkRequestResult] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
