# This file was auto-generated by Fern from our API Definition.

import typing

NetworkRequestStatus = typing.Union[
    typing.Literal["started", "challenge-issued", "completed", "failed", "expired"], typing.Any
]
