# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .field_base import FieldBase


class NumberField(FieldBase):
    """
    Numeric input with optional `min` / `max` bounds and `step` granularity.
    """

    placeholder: typing.Optional[str] = pydantic.Field(default=None)
    """
    Ghost text shown inside the input while it's empty.
    """

    min: typing.Optional[float] = pydantic.Field(default=None)
    """
    Minimum accepted value.
    """

    max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum accepted value.
    """

    step: typing.Optional[float] = pydantic.Field(default=None)
    """
    Increment between valid values. For example, `step: 0.5` lets the user enter 1, 1.5, 2, etc.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
