# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .field_base import FieldBase


class RangeField(FieldBase):
    """
    Slider input. `min`/`max` define the bounds, `step` the granularity.
    """

    min: typing.Optional[float] = pydantic.Field(default=None)
    """
    Lower bound of the slider.
    """

    max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Upper bound of the slider.
    """

    step: typing.Optional[float] = pydantic.Field(default=None)
    """
    Increment between adjacent slider stops.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
