# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .field_base import FieldBase


class RatingField(FieldBase):
    """
    Star rating 1..`max`. Submitted value is the selected integer.
    """

    min: typing.Optional[int] = pydantic.Field(default=None)
    """
    Minimum allowed rating. `0` means the submitter can clear their selection.
    """

    max: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of stars rendered.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
