# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .rcs_campaign_summary_status import RcsCampaignSummaryStatus


class RcsCampaignSummary(UniversalBaseModel):
    campaign_id: typing_extensions.Annotated[str, FieldMetadata(alias="campaignId")] = pydantic.Field()
    """
    Unique identifier for the RCS campaign.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the campaign.
    """

    status: RcsCampaignSummaryStatus = pydantic.Field()
    """
    Current status of the campaign.
    """

    brand_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="brandId")] = pydantic.Field(
        default=None
    )
    """
    Brand ID associated with this campaign.
    """

    agent_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="agentId")] = pydantic.Field(
        default=None
    )
    """
    RCS agent ID associated with this campaign.
    """

    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt")] = pydantic.Field()
    """
    ISO 8601 timestamp of when the campaign was created.
    """

    updated_at: typing_extensions.Annotated[str, FieldMetadata(alias="updatedAt")] = pydantic.Field()
    """
    ISO 8601 timestamp of when the campaign was last updated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
