# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .rcs_cards_cards_item_media_height import RcsCardsCardsItemMediaHeight
from .rich_button import RichButton


class RichCard(UniversalBaseModel):
    """
    Individual card containing title, optional media, and action buttons.
    """

    buttons: typing.Optional[typing.List[RichButton]] = pydantic.Field(default=None)
    """
    While buttons resemble quick replies, they remain on screen after being clicked and are card-specific. <br><br>
    **Limit:** 4 max
    """

    media: typing.Optional[str] = pydantic.Field(default=None)
    """
    Media file URLs to send.
    """

    media_height: typing_extensions.Annotated[
        typing.Optional[RcsCardsCardsItemMediaHeight], FieldMetadata(alias="mediaHeight")
    ] = pydantic.Field(default=None)
    """
    Height of the card media. <br><br>
    **Default:** `MEDIUM` <br>
    **Valid for:** Carousel cards and vertical standalone cards. <br>
    **Not valid for:** Horizontal standalone cards. <br>
    **Requires:** The card must include a `media` field.
    """

    subtitle: typing.Optional[str] = pydantic.Field(default=None)
    """
    Secondary text displayed below the title for additional context.
    """

    title: str = pydantic.Field()
    """
    Title displayed on the card.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
