# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .field_base import FieldBase
from .form_field_option import FormFieldOption


class SelectField(FieldBase):
    """
    Single-select dropdown.
    """

    options: typing.List[FormFieldOption] = pydantic.Field()
    """
    Choices shown in the dropdown. At least one is required.
    """

    placeholder: typing.Optional[str] = pydantic.Field(default=None)
    """
    Placeholder row shown when no option is selected (e.g. "Select…").
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
