# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .message_schedule import MessageSchedule
from .rich_standalone_card_options import RichStandaloneCardOptions
from .send_rcs_card_options_card_width import SendRcsCardOptionsCardWidth
from .tracking import Tracking


class SendRichCardsOptions(UniversalBaseModel):
    """
    Configure how your RCS message is sent and tracked.
    """

    schedule: typing.Optional[MessageSchedule] = None
    tracking: typing.Optional[Tracking] = None
    transcode: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Media files and card media will be transcoded to a supported RCS format. This adds a small delay to sending the message. Ignored for rich text messages.
    """

    validate_: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="validate")] = pydantic.Field(
        default=None
    )
    """
    Validate your message for any unsupported files. <br>
    
    If failed, errors will be thrown and the message will not send.
    """

    standalone_card: typing.Optional[RichStandaloneCardOptions] = pydantic.Field(default=None)
    """
    Configure standalone card layout options for enhanced visual presentation.
    
    > **⚠️ Important Restriction**
    >
    > This option is **only valid for single card messages** with static media. Using it with multiple cards will cause the request to fail with a validation error.
    > GIFs and videos are not supported and will be rendered as vertical cards.
    """

    card_width: typing_extensions.Annotated[
        typing.Optional[SendRcsCardOptionsCardWidth], FieldMetadata(alias="cardWidth")
    ] = pydantic.Field(default=None)
    """
    Width of each card in a carousel. <br><br>
    **Default:** `MEDIUM` <br>
    **Valid for:** Multi-card messages (2 to 10 cards). <br>
    **Not valid for:** Single-card messages. Setting it with one card fails validation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
