# This file was auto-generated by Fern from our API Definition.

import typing

from .send_form_via_rcs_params import SendFormViaRcsParams
from .send_form_via_sms_params import SendFormViaSmsParams

SendFormParams = typing.Union[SendFormViaRcsParams, SendFormViaSmsParams]
