# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .send_form_options import SendFormOptions
from .send_form_via_rcs_request_fallback import SendFormViaRcsRequestFallback
from .send_form_via_rcs_request_form import SendFormViaRcsRequestForm


class SendFormViaRcsParams(UniversalBaseModel):
    """
    Send a form from an RCS agent. `from` must be an `agent_*` id.
    """

    from_: typing_extensions.Annotated[str, FieldMetadata(alias="from")] = pydantic.Field()
    """
    RCS agent id (`agent_*`).
    """

    to: typing.Optional[str] = pydantic.Field(default=None)
    """
    Recipient phone in E.164. When present Pinnacle delivers the form URL via RCS (or the configured fallback) and FORM.SUBMISSION fires with `submission.to` populated. When omitted the call returns a submission URL without dispatching any message and the webhook later fires with `submission.to: null`.
    """

    form: SendFormViaRcsRequestForm = pydantic.Field()
    """
    Existing form id or an inline definition that mints a new form for this send.
    """

    fallback: typing.Optional[SendFormViaRcsRequestFallback] = pydantic.Field(default=None)
    """
    When RCS is unavailable on the recipient's device, fall back to SMS from this number. Requires `to`.
    """

    options: typing.Optional[SendFormOptions] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
