# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .send_form_options import SendFormOptions
from .send_form_via_sms_request_form import SendFormViaSmsRequestForm


class SendFormViaSmsParams(UniversalBaseModel):
    """
    Send a form from a phone number. `from` must be an E.164 phone.
    """

    from_: typing_extensions.Annotated[str, FieldMetadata(alias="from")] = pydantic.Field()
    """
    Sender phone in E.164.
    """

    to: typing.Optional[str] = pydantic.Field(default=None)
    """
    Recipient phone in E.164. Omit to mint a URL-only form without sending a message.
    """

    form: SendFormViaSmsRequestForm
    options: typing.Optional[SendFormOptions] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
