# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .network_request_id import NetworkRequestId


class SilentAuthResponse_Hosted(UniversalBaseModel):
    format: typing.Literal["hosted"] = "hosted"
    request_id: typing_extensions.Annotated[NetworkRequestId, FieldMetadata(alias="requestId")]
    browser_url: typing_extensions.Annotated[str, FieldMetadata(alias="browserUrl")]
    expires_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="expiresAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SilentAuthResponse_Json(UniversalBaseModel):
    format: typing.Literal["json"] = "json"
    request_id: typing_extensions.Annotated[NetworkRequestId, FieldMetadata(alias="requestId")]
    json_url: typing_extensions.Annotated[str, FieldMetadata(alias="jsonUrl")]
    expires_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="expiresAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


SilentAuthResponse = typing.Union[SilentAuthResponse_Hosted, SilentAuthResponse_Json]
