# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .network_request_id import NetworkRequestId
from .silent_auth_check_response_status import SilentAuthCheckResponseStatus


class SilentAuthCheckResponse(UniversalBaseModel):
    request_id: typing_extensions.Annotated[NetworkRequestId, FieldMetadata(alias="requestId")]
    status: SilentAuthCheckResponseStatus = pydantic.Field()
    """
    Terminal verification result after exchanging a device flow code. `completed` means the phone number was verified; `failed` means the verification did not complete successfully. To inspect pending lifecycle states, use [Get Network Request](/api-reference/network/get-network-request).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
