# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .network_insight_status import NetworkInsightStatus
from .network_request_id import NetworkRequestId


class SimSwapResponse(UniversalBaseModel):
    request_id: typing_extensions.Annotated[NetworkRequestId, FieldMetadata(alias="requestId")]
    status: NetworkInsightStatus
    sim_swapped: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="simSwapped")] = pydantic.Field(
        default=None
    )
    """
    Whether the SIM changed during the requested window. Null means the carrier insight was unavailable, unsupported, or failed.
    """

    latest_sim_swap_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="latestSimSwapAt")
    ] = pydantic.Field(default=None)
    """
    Timestamp of the latest SIM change in the requested window, when the carrier provides it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
