# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class SimulateMessageInput(UniversalBaseModel):
    """
    User message payload. At least one of `text` or `mediaUrls` must be non-empty.
    Send only `text` to simulate an inbound SMS; include `mediaUrls` to simulate an inbound MMS.
    """

    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Text message sent by the user.
    """

    media_urls: typing_extensions.Annotated[typing.Optional[typing.List[str]], FieldMetadata(alias="mediaUrls")] = (
        pydantic.Field(default=None)
    )
    """
    URLs of media files sent by the user.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
