# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .subscriber_match_result import SubscriberMatchResult


class SubscriberMatchResponseMatches(UniversalBaseModel):
    """
    Match strength for each evaluated subscriber attribute.

    - `exact`: Carrier record matches the submitted value exactly.
    - `high`: Strong match with minor formatting or normalization differences.
    - `partial`: Some parts match, but the value is not a strong match.
    - `low`: Weak match.
    - `none`: Carrier record does not match the submitted value.
    - `unavailable`: Carrier could not evaluate this attribute.
    - `included-with-address-match`: Attribute was evaluated as part of the overall address match.
    - `unknown`: Carrier returned a match value Pinnacle does not recognize yet.
    """

    id_document: typing_extensions.Annotated[
        typing.Optional[SubscriberMatchResult], FieldMetadata(alias="idDocument")
    ] = None
    given_name: typing_extensions.Annotated[
        typing.Optional[SubscriberMatchResult], FieldMetadata(alias="givenName")
    ] = None
    family_name: typing_extensions.Annotated[
        typing.Optional[SubscriberMatchResult], FieldMetadata(alias="familyName")
    ] = None
    address: typing.Optional[SubscriberMatchResult] = None
    street_name: typing_extensions.Annotated[
        typing.Optional[SubscriberMatchResult], FieldMetadata(alias="streetName")
    ] = None
    street_number: typing_extensions.Annotated[
        typing.Optional[SubscriberMatchResult], FieldMetadata(alias="streetNumber")
    ] = None
    postal_code: typing_extensions.Annotated[
        typing.Optional[SubscriberMatchResult], FieldMetadata(alias="postalCode")
    ] = None
    locality: typing.Optional[SubscriberMatchResult] = None
    region: typing.Optional[SubscriberMatchResult] = None
    country: typing.Optional[SubscriberMatchResult] = None
    street_number_suffix: typing_extensions.Annotated[
        typing.Optional[SubscriberMatchResult], FieldMetadata(alias="streetNumberSuffix")
    ] = None
    birthdate: typing.Optional[SubscriberMatchResult] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
