# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .network_insight_status import NetworkInsightStatus
from .network_request_id import NetworkRequestId
from .subscriber_match_response_matches import SubscriberMatchResponseMatches


class SubscriberMatchResponse(UniversalBaseModel):
    request_id: typing_extensions.Annotated[NetworkRequestId, FieldMetadata(alias="requestId")]
    status: NetworkInsightStatus
    matches: SubscriberMatchResponseMatches = pydantic.Field()
    """
    Match strength for each evaluated subscriber attribute.
    
    - `exact`: Carrier record matches the submitted value exactly.
    - `high`: Strong match with minor formatting or normalization differences.
    - `partial`: Some parts match, but the value is not a strong match.
    - `low`: Weak match.
    - `none`: Carrier record does not match the submitted value.
    - `unavailable`: Carrier could not evaluate this attribute.
    - `included-with-address-match`: Attribute was evaluated as part of the overall address match.
    - `unknown`: Carrier returned a match value Pinnacle does not recognize yet.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
