# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .field_base import FieldBase


class TextareaField(FieldBase):
    """
    Multi-line text input for longer free-form answers.
    """

    placeholder: typing.Optional[str] = pydantic.Field(default=None)
    """
    Ghost text shown inside the input while it's empty.
    """

    pattern: typing.Optional[str] = pydantic.Field(default=None)
    """
    Regex the value must match. Same RE2 safety check as `TextField.pattern`.
    """

    min_length: typing.Optional[int] = pydantic.Field(default=None)
    """
    Minimum number of characters the submitter must enter.
    """

    max_length: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum number of characters the submitter may enter.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
