# This file was auto-generated by Fern from our API Definition.

import typing

TollFreeCampaignSummaryStatus = typing.Union[
    typing.Literal["INCOMPLETE", "IN REVIEW", "VERIFIED", "FAILED"], typing.Any
]
