# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .user_button_press_request_user_location_location import UserButtonPressRequestUserLocationLocation
from .user_button_press_send_location_lat_long import UserButtonPressSendLocationLatLong


class UserButtonPress_Trigger(UniversalBaseModel):
    """
    Discriminated union of button presses that can be simulated for a user.
    """

    type: typing.Literal["trigger"] = "trigger"
    title: str
    metadata: typing.Optional[str] = None
    payload: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class UserButtonPress_OpenUrl(UniversalBaseModel):
    """
    Discriminated union of button presses that can be simulated for a user.
    """

    type: typing.Literal["openUrl"] = "openUrl"
    title: str
    metadata: typing.Optional[str] = None
    payload: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class UserButtonPress_Call(UniversalBaseModel):
    """
    Discriminated union of button presses that can be simulated for a user.
    """

    type: typing.Literal["call"] = "call"
    title: str
    metadata: typing.Optional[str] = None
    payload: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class UserButtonPress_ScheduleEvent(UniversalBaseModel):
    """
    Discriminated union of button presses that can be simulated for a user.
    """

    type: typing.Literal["scheduleEvent"] = "scheduleEvent"
    title: str
    metadata: typing.Optional[str] = None
    event_start_time: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="eventStartTime")] = None
    event_end_time: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="eventEndTime")] = None
    event_title: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="eventTitle")] = None
    event_description: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="eventDescription")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class UserButtonPress_SendLocation(UniversalBaseModel):
    """
    Discriminated union of button presses that can be simulated for a user.
    """

    type: typing.Literal["sendLocation"] = "sendLocation"
    title: str
    metadata: typing.Optional[str] = None
    name: typing.Optional[str] = None
    lat_long: typing_extensions.Annotated[
        typing.Optional[UserButtonPressSendLocationLatLong], FieldMetadata(alias="latLong")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class UserButtonPress_RequestUserLocation(UniversalBaseModel):
    """
    Discriminated union of button presses that can be simulated for a user.
    """

    type: typing.Literal["requestUserLocation"] = "requestUserLocation"
    title: str
    metadata: typing.Optional[str] = None
    location: typing.Optional[UserButtonPressRequestUserLocationLocation] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


UserButtonPress = typing.Union[
    UserButtonPress_Trigger,
    UserButtonPress_OpenUrl,
    UserButtonPress_Call,
    UserButtonPress_ScheduleEvent,
    UserButtonPress_SendLocation,
    UserButtonPress_RequestUserLocation,
]
