# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user_button_press_request_user_location_location import UserButtonPressRequestUserLocationLocation


class UserButtonPressRequestUserLocation(UniversalBaseModel):
    """
    Simulates when a user presses a `requestUserLocation` button.
    """

    title: str = pydantic.Field()
    """
    Name of the button that you want to press.
    """

    metadata: typing.Optional[str] = pydantic.Field(default=None)
    """
    Metadata attached to the button.
    """

    location: typing.Optional[UserButtonPressRequestUserLocationLocation] = pydantic.Field(default=None)
    """
    Location the simulated user responded with.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
