# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .user_button_press_send_location_lat_long import UserButtonPressSendLocationLatLong


class UserButtonPressSendLocation(UniversalBaseModel):
    """
    Simulates when a user presses a `sendLocation` button.
    """

    title: str = pydantic.Field()
    """
    Name of the button that you want to press.
    """

    metadata: typing.Optional[str] = pydantic.Field(default=None)
    """
    Metadata attached to the button.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the location shared.
    """

    lat_long: typing_extensions.Annotated[
        typing.Optional[UserButtonPressSendLocationLatLong], FieldMetadata(alias="latLong")
    ] = pydantic.Field(default=None)
    """
    Shared coordinates.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
