# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .whitelisted_number_summary_status import WhitelistedNumberSummaryStatus


class WhitelistedNumberSummary(UniversalBaseModel):
    number: str = pydantic.Field()
    """
    Whitelisted phone number in E.164 format.
    """

    status: WhitelistedNumberSummaryStatus = pydantic.Field()
    """
    Current status of the whitelisted number.
    """

    agent_id: typing_extensions.Annotated[str, FieldMetadata(alias="agentId")] = pydantic.Field()
    """
    Agent ID this number is whitelisted for.
    """

    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt")] = pydantic.Field()
    """
    ISO 8601 timestamp of when the number was whitelisted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
