# This file was auto-generated by Fern from our API Definition.

import typing

ListMessagesRequestStatus = typing.Union[
    typing.Literal[
        "PENDING", "SENT", "SEND_FAILED", "DELIVERED", "DELIVERY_FAILED", "RECEIVED", "READ", "QUEUED", "FALLBACK_SENT"
    ],
    typing.Any,
]
