# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.list_form_submissions_response import ListFormSubmissionsResponse
from .raw_client import AsyncRawSubmissionsClient, RawSubmissionsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SubmissionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSubmissionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSubmissionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSubmissionsClient
        """
        return self._raw_client

    def list(
        self,
        id: str,
        *,
        page_index: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListFormSubmissionsResponse:
        """
        Paginated list of completed submissions for a form, newest first. Each row includes the submitted `data` keyed by field `key`, the sender/recipient, IP, user-agent, and timestamps.

        Parameters
        ----------
        id : str
            The unique identifier of the form whose submissions you want to list.
            <br><br> This identifier is a string that always begins with the prefix `form_`, for example: `form_Oy2n7iUoi9CJwUU6`.

        page_index : typing.Optional[int]
            Zero-based page index.

        page_size : typing.Optional[int]
            Number of submissions to return in a single page. Max 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFormSubmissionsResponse
            Paginated list of submissions.

        Examples
        --------
        from rcs import Pinnacle

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.forms.submissions.list(
            id="form_Oy2n7iUoi9CJwUU6",
            page_index=0,
            page_size=20,
        )
        """
        _response = self._raw_client.list(
            id, page_index=page_index, page_size=page_size, request_options=request_options
        )
        return _response.data


class AsyncSubmissionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSubmissionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSubmissionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSubmissionsClient
        """
        return self._raw_client

    async def list(
        self,
        id: str,
        *,
        page_index: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListFormSubmissionsResponse:
        """
        Paginated list of completed submissions for a form, newest first. Each row includes the submitted `data` keyed by field `key`, the sender/recipient, IP, user-agent, and timestamps.

        Parameters
        ----------
        id : str
            The unique identifier of the form whose submissions you want to list.
            <br><br> This identifier is a string that always begins with the prefix `form_`, for example: `form_Oy2n7iUoi9CJwUU6`.

        page_index : typing.Optional[int]
            Zero-based page index.

        page_size : typing.Optional[int]
            Number of submissions to return in a single page. Max 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFormSubmissionsResponse
            Paginated list of submissions.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.forms.submissions.list(
                id="form_Oy2n7iUoi9CJwUU6",
                page_index=0,
                page_size=20,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            id, page_index=page_index, page_size=page_size, request_options=request_options
        )
        return _response.data
