# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.e_164_phone_number import E164PhoneNumber
from ...types.subscriber_match_attributes import SubscriberMatchAttributes
from ...types.subscriber_match_response import SubscriberMatchResponse
from .raw_client import AsyncRawSubscriberMatchClient, RawSubscriberMatchClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SubscriberMatchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSubscriberMatchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSubscriberMatchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSubscriberMatchClient
        """
        return self._raw_client

    def check(
        self,
        *,
        phone_number: E164PhoneNumber,
        attributes: SubscriberMatchAttributes,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriberMatchResponse:
        """
        Compare user-provided identity details against the carrier's subscriber record. Results return match strength per attribute, so you can use partial signals without receiving carrier PII.

        <Note>
          Limited availability. Contact [founders@pinnacle.sh](mailto:founders@pinnacle.sh) to request access.
        </Note>

        Parameters
        ----------
        phone_number : E164PhoneNumber

        attributes : SubscriberMatchAttributes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriberMatchResponse
            Returns match strength for each evaluated subscriber attribute.

        Examples
        --------
        from rcs import Pinnacle, SubscriberMatchAttributes

        client = Pinnacle(
            api_key="YOUR_API_KEY",
        )
        client.network.subscriber_match.check(
            phone_number="+14155550123",
            attributes=SubscriberMatchAttributes(
                given_name="Jane",
                family_name="Doe",
                street_name="Market Street",
                street_number="123",
                postal_code="94105",
                locality="San Francisco",
                region="CA",
                country="US",
                birthdate="1990-01-31",
            ),
        )
        """
        _response = self._raw_client.check(
            phone_number=phone_number, attributes=attributes, request_options=request_options
        )
        return _response.data


class AsyncSubscriberMatchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSubscriberMatchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSubscriberMatchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSubscriberMatchClient
        """
        return self._raw_client

    async def check(
        self,
        *,
        phone_number: E164PhoneNumber,
        attributes: SubscriberMatchAttributes,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriberMatchResponse:
        """
        Compare user-provided identity details against the carrier's subscriber record. Results return match strength per attribute, so you can use partial signals without receiving carrier PII.

        <Note>
          Limited availability. Contact [founders@pinnacle.sh](mailto:founders@pinnacle.sh) to request access.
        </Note>

        Parameters
        ----------
        phone_number : E164PhoneNumber

        attributes : SubscriberMatchAttributes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriberMatchResponse
            Returns match strength for each evaluated subscriber attribute.

        Examples
        --------
        import asyncio

        from rcs import AsyncPinnacle, SubscriberMatchAttributes

        client = AsyncPinnacle(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.network.subscriber_match.check(
                phone_number="+14155550123",
                attributes=SubscriberMatchAttributes(
                    given_name="Jane",
                    family_name="Doe",
                    street_name="Market Street",
                    street_number="123",
                    postal_code="94105",
                    locality="San Francisco",
                    region="CA",
                    country="US",
                    birthdate="1990-01-31",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.check(
            phone_number=phone_number, attributes=attributes, request_options=request_options
        )
        return _response.data
